module.exports = [
  {
    name: "PM Kisan Samman Nidhi",
    description:
      "Income support scheme for small and marginal farmer families providing financial assistance per year in three equal instalments.",
    category: "Agriculture",
    benefit: "₹6,000 per year in three equal instalments, directly transferred to beneficiaries' bank accounts.",
    deadline: "Ongoing",
    sourceUrl: "https://www.myscheme.gov.in/schemes/pm-kisan",
    ministry: "Ministry of Agriculture & Farmers Welfare",
    eligibilityCriteria: {
      minAge: null,
      maxAge: null,
      maxIncome: null,
      gender: "any",
      states: [],
      casteCategory: [],
      occupation: ["farmer"],
    },
    documents: ["Aadhaar Card", "Bank Account Details", "Land Ownership Documents"],
    scrapedAt: new Date(),
  },
  {
    name: "PM Ujjwala Yojana",
    description:
      "Scheme to provide LPG connections to women members of below poverty line households to ensure clean cooking fuel.",
    category: "Welfare",
    benefit: "Financial support for LPG connection including security deposit for cylinder and pressure regulator.",
    deadline: "Ongoing",
    sourceUrl: "https://www.myscheme.gov.in/schemes/pmuy",
    ministry: "Ministry of Petroleum & Natural Gas",
    eligibilityCriteria: {
      minAge: 18,
      maxAge: null,
      maxIncome: null,
      gender: "female",
      states: [],
      casteCategory: [],
      occupation: [],
    },
    documents: ["Aadhaar Card", "Ration Card", "Bank Account Details"],
    scrapedAt: new Date(),
  },
  {
    name: "National Means-cum-Merit Scholarship",
    description:
      "Scholarship scheme to provide financial support to meritorious students from economically weaker sections to reduce dropouts at class VIII and encourage them to continue education.",
    category: "Education",
    benefit: "Annual scholarship for selected students from class IX to XII, subject to eligibility.",
    deadline: "Ongoing",
    sourceUrl: "https://www.myscheme.gov.in/schemes/nmmss",
    ministry: "Ministry of Education",
    eligibilityCriteria: {
      minAge: null,
      maxAge: null,
      maxIncome: 150000,
      gender: "any",
      states: [],
      casteCategory: [],
      occupation: ["student"],
    },
    documents: ["Aadhaar Card", "Income Certificate", "School ID Card"],
    scrapedAt: new Date(),
  },
];

